// Contatos da URE Suzano.
//
// Para atualizar, edite só este arquivo: os cards, a busca, o menu de setores,
// os totais e o "Plantão de hoje" são gerados a partir destas listas.
//
// Campos de cada pessoa:
//   name, role, phone, email  -> obrigatórios (use "" quando não houver)
//   group    -> agrupa a pessoa dentro do setor (ex.: pasta da EEC)
//   shift    -> plantão, no formato "3ª Feira das 15h as 17h" ou "s/plantão"
//   folders  -> pastas/projetos (lista)
//   schools  -> escolas { public, private, substitute } (entram na busca)
//   note     -> aviso curto (ex.: afastamento)
//
// Bases usadas:
//   EEC  -> https://samucacs.github.io/fluxograma-ure/eec.html
//   ESE  -> https://pagina-supervisao-ese.vercel.app/ (SUPERVISÃO 2026 - ORGANIZAÇÃO DOS SETORES 16/09/26)
//
// Cores disponíveis para "color": green, purple, blue, orange, indigo, teal, red, pink.

const database = [
  {
    sector: "Gabinete / Assessoria",
    icon: "fa-building",
    color: "green",
    members: [
      {
        name: "GABINETE",
        role: "Recepção Gabinete",
        phone: "4746-7214 | 4746-7220",
        email: "suz@educacao.sp.gov.br",
      },
      {
        name: "GABINETE",
        role: "Recepção Gabinete",
        phone: "4746-7220",
        email: "suz@educacao.sp.gov.br",
      },
    ],
  },
  {
    sector: "ESE - Equipe de Supervisão",
    icon: "fa-eye",
    color: "purple",
    info: "Plantão: 4746-7227 / 4746-7228",
    link: "https://pagina-supervisao-ese.vercel.app/",
    linkLabel: "Conheça nossa Supervisão",
    members: [
      {
        name: "Alex Bonfim",
        role: "Supervisor",
        phone: "",
        email: "",
        shift: "s/plantão",
        schools: {
          public: [
            "IIJIMA",
            "JOSE BENEDITO LEITE BARTHOLOMEI PROFESSOR",
            "MARIA ELISA DE AZEVEDO CINTRA PROF",
          ],
          private: [],
          substitute: [],
        },
      },
      {
        name: "Andrea R. Moraes do Carmo Oliveira",
        role: "Supervisor",
        phone: "4746-7211",
        email: "andrea.moraes@educacao.sp.gov.br",
        shift: "3ª Feira das 15h as 17h",
        folders: ["ED ESPECIAL", "PRONTOS PRO MUNDO", "CEL"],
        schools: {
          public: [
            "BRASILIO MACHADO NETO COMENDADOR",
            "CONJUNTO HABITACIONAL PARQUE DOURADO II",
            "ELIANE APARECIDA DANTAS DA SILVA PROFESSORA",
            "JARDIM SAO PAULO II",
          ],
          private: ["COLÉGIO SILOGEU", "INSTITUTO EDUCACIONAL FORMAÇÃO SUZANO"],
          substitute: [
            "TOKUZO TERAZAKI",
            "ANTONIO VALDEMAR GALO VEREADOR",
            "EDIR DO COUTO ROSA PROFESSOR",
            "TACITO ZANCHETTA PREFEITO",
          ],
        },
      },
      {
        name: "Cintia Souza Borges",
        role: "Supervisor",
        phone: "4746-7224",
        email: "cintia.borges01@educacao.sp.gov.br",
        shift: "6ª Feira das 13h as 15h",
        folders: ["APOIO PRESENCIAL", "ED. ESPECIAL", "APAE"],
        schools: {
          public: [
            "TACITO ZANCHETTA PREFEITO",
            "ANTONIO GARCIA VEREADOR",
            "YOLANDA BASSI PROFESSORA",
          ],
          private: [
            "COLÉGIO ELITE",
            "APAE - FERRAZ DE VASCONCELOS",
            "COLÉGIO OBJETIVO - UNID. SUZANO",
          ],
          substitute: [
            "BRASILIO MACHADO NETO COMENDADOR",
            "LEDA FERNANDES LOPES PROFESSORA",
          ],
        },
      },
      {
        name: "Elaine Ferreira Cunha",
        role: "Supervisor",
        phone: "4746-6026",
        email: "elaine.cunha1@educacao.sp.gov.br",
        shift: "4ª Feira das 10h as 12h",
        folders: ["ATRIBUIÇÃO", "SEPES", "EXPANSÃO DIURNO"],
        schools: {
          public: [
            "ANDERSON DA SILVA SOARES",
            "CHOJIRO SEGAWA",
            "JOVIANO SATLER DE LIMA PROFESSOR",
          ],
          private: [
            "COLÉGIO VILA FIGUEIRA",
            "COLÉGIO CRISTÃO NOVA GERAÇÃO",
            "COLEGIO SOL",
          ],
          substitute: [
            "IGNES CORREA ALLEN PROFESSORA",
            "JOSE PAPAIZ PROFESSOR",
            "OLAVO LEONEL FERREIRA PROFESSOR",
          ],
        },
      },
      {
        name: "Elisabete Gomes Benatti",
        role: "Supervisor",
        phone: "4746-6033",
        email: "elisabete.gomes01@educacao.sp.gov.br",
        shift: "6ª Feira das 08h as 10h",
        folders: ["EDUCAÇÃO ESPECIAL", "AVALIAÇÃO EXTERNA", "SEAFIN"],
        schools: {
          public: [
            "HELENA ZERRENNER",
            "JOSE EDUARDO VIEIRA RADUAN DOUTOR",
            "JACQUES YVES COUSTEAU COMANDANTE",
          ],
          private: ["COLEGIO EDUCAR", "COLEGIO ALICERCE DO SABER"],
          substitute: [
            "ANIS FADUL DOUTOR",
            "PAULO KOBAYASHI PROFESSOR",
            "ANTONIO BRASILIO MENEZES DA FONSECA PROF",
            "MANUEL DOS SANTOS PAIVA",
          ],
        },
      },
      {
        name: "Elisangela Andrea Marques Araujo",
        role: "Supervisor",
        phone: "4746-7211",
        email: "elisangela.araujo@educacao.sp.gov.br",
        shift: "5ª Feira das 08h as 10h",
        folders: [
          "ALUNO MONITOR DO BEEM - REGULAR",
          "CONSELHO MUNICIPAL FERRAZ",
          "ITINERÁRIO FORMATIVO",
          "AUDIENCIA CONCENTRADA",
          "EQUIVALÊNCIA DE ESTUDOS",
        ],
        schools: {
          public: [
            "GIOVANNI BATTISTA RAFFO PROFESSOR DOUTOR",
            "GERALDO JUSTINIANO DE REZENDE SILVA PROF",
            "TOKUZO TERAZAKI",
            "MARTHA CALIXTO CAZAGRANDE",
          ],
          private: ["COLÉGIO TÉCNICO SÃO FRANCISCO", "COLÉGIO FERREIRA MASTER"],
          substitute: [
            "MARIA ELISA DE AZEVEDO CINTRA PROF",
            "LANDIA SANTOS BATISTA PROFESSORA",
            "ZELIA GATTAI AMADO",
            "JANDYRA COUTINHO PROFESSORA",
          ],
        },
      },
      {
        name: "Elizabeth das Neves Alves Pereira",
        role: "Supervisor",
        phone: "4746-6024",
        email: "elizabeth.pereira@educacao.sp.gov.br",
        shift: "5ª Feira das 10h as 12h",
        folders: [
          "CIVICO MILITAR",
          "ITINERÁRIO FORMATIVO",
          "EXPANSÃO NOTURNO",
          "AVALIAÇÕES EXTERNAS",
        ],
        schools: {
          public: [
            "ANGELA SUELI PONTES DIAS PROFESSORA",
            "EDIR DO COUTO ROSA PROFESSOR",
            "LANDIA SANTOS BATISTA PROFESSORA",
          ],
          private: ["COLÉGIO UNISUZ", "COLEGIO INTEGRADO LUMBINI"],
          substitute: [
            "LUCY FRANCO KOWALSKI PROFESSORA",
            "LUIZA HIDAKA PROFESSORA",
            "SEBASTIAO PEREIRA VIDAL",
            "JOSE CAMILO DE ANDRADE",
          ],
        },
      },
      {
        name: "Fabiana Vanelli Candido",
        role: "Supervisor",
        phone: "4746-7225",
        email: "fabiana.candido@educacao.sp.gov.br",
        shift: "6ª Feira das 15h as 17h",
        folders: [
          "PROF TUTOR A.I / ANOS INICIAIS",
          "GRÊMIO ESTUDANTIL",
          "APOIO PRESENCIAL",
          "ESTAGIO SUPERVISIONADO",
        ],
        schools: {
          public: [
            "CARLINDO REIS",
            "JUSTINO MARCONDES RANGEL PROFESSOR",
            "RAUL BRASIL PROFESSOR",
            "LUCY FRANCO KOWALSKI PROFESSORA",
          ],
          private: ["COLÉGIO CORREA", "COLÉGIO DIOCESANO PAULO VI"],
          substitute: [
            "BENEDITA DE CAMPOS MARCOLONGO PROFESSOR",
            "GERALDO JUSTINIANO DE REZENDE SILVA PROF",
            "JUSSARA FEITOSA SOMSCHKE PROFESSORA",
            "TOCHICHICO YOCHICAVA PROFESSOR",
          ],
        },
      },
      {
        name: "Gisele Gonçalves Callado",
        role: "Supervisor",
        phone: "4746-7226",
        email: "gisele.callado@educacao.sp.gov.br",
        shift: "3ª Feira das 8h as 10h",
        folders: ["SALA DE LEITURA", "ATRIBUIÇÃO", "ESTAGIO SUPERVISIONADO"],
        schools: {
          public: [
            "ANTONIO RODRIGUES DE ALMEIDA",
            "GILBERTO DE CARVALHO PROFESSOR",
            "JUSSARA FEITOSA DOMSCHKE PROFESSORA",
            "ZELIA GATTAI AMADO",
          ],
          private: ["COLÉGIO GAMALIEL", "NUCLEO EDUCACIONAL FERRAZENSE"],
          substitute: [
            "ANGELA SUELI PONTES DIAS PROFESSORA",
            "RAUL BRASIL PROFESSOR",
            "JUSTINO MARCONDES RANGEL PROFESSOR",
            "MARTHA CALIXTO CAZAGRANDE",
          ],
        },
      },
      {
        name: "Lethycia Regina Rodrigues",
        role: "Supervisor",
        phone: "4746-6020",
        email: "lethycia.rodrigues@educacao.sp.gov.br",
        shift: "4ª Feira das 13h as 15h",
        folders: [
          "ATRIBUIÇÃO",
          "EJA",
          "ESTAGIO PROBATÓRIO",
          "ERER",
          "PROATI",
          "SubCADA",
        ],
        schools: {
          public: [
            "EUCLIDES IGESCA",
            "MORATO DE OLIVEIRA DOUTOR",
            "MARIO MANOEL DANTAS DE AQUINO PROFESSOR",
          ],
          private: ["COLÉGIO TÉCNICO SÃO BENTO"],
          substitute: [
            "MASAITE SEKINE PROFESSOR",
            "PAULO AMERICO PAGANUCCI PROFESSOR",
            "CHOJIRO SEGAWA",
            "GIOVANNI BATISTA RAFFO PROF. DR.",
          ],
        },
      },
      {
        name: "Mirela de Oliveira Roman",
        role: "Supervisor",
        phone: "4746-5023",
        email: "mirela.roman@educacao.sp.gov.br",
        shift: "6ª Feira das 10h as 12h",
        folders: [
          "PROGRAMAS E PROJ - MEC",
          "GRÊMIO ESTUDANTIL",
          "CONSELHO E APM (COLEGIADOS)",
        ],
        schools: {
          public: [
            "ANIS FADUL DOUTOR",
            "ANTONIO BRASILIO MENEZES DA FONSECA PROF",
            "PAULO KOBAYASHI PROFESSOR",
            "MANUEL DOS SANTOS PAIVA",
          ],
          private: [
            "INSTITUTO EDUCACIONAL LUTERANO",
            "NUCLEO EDUCACIONAL NOVOS HORIZONTES",
          ],
          substitute: [
            "JACQUES YVES COUSTEAU COMANDANTE",
            "HELENA ZERRENNER",
            "JOSE EDUARDO VIEIRA RADUAN DOUTOR",
          ],
        },
      },
      {
        name: "Mirian Miya",
        role: "Supervisor",
        phone: "4746-7213",
        email: "mirian.miya@educacao.sp.gov.br",
        shift: "4ª Feira das 08h as 10h",
        folders: [
          "APURAÇÃO PRELIMINAR RES.06/26",
          "PONTO FOCAL EEC",
          "PROF TUTOR ANOS FINAIS",
        ],
        schools: {
          public: [
            "MASAITI SEKINE PROFESSOR",
            "ALICE ROMANOS PROFESSORA",
            "PAULO AMERICO PAGANUCCI PROFESSOR",
          ],
          private: [
            "INSTITUTO EDUCACIONAL ANDRADE",
            "COLEGIO TÉCNICO SANTA LUZIA",
          ],
          substitute: [
            "EUCLIDES IGESCA",
            "MARIO MANOEL DANTAS DE AQUINO PROFESSOR",
            "MORATO DE OLIVEIRA DOUTOR",
            "JOSE BENEDITO LEITE BARTHOLOMEI PROFESSOR",
          ],
        },
      },
      {
        name: "Núbia Ferreira de Melo",
        role: "Supervisor",
        phone: "4746-5025",
        email: "nubia.melo@educacao.sp.gov.br",
        shift: "3ª Feira das 13h as 15h",
        folders: ["CONVIVA", "ERER"],
        schools: {
          public: ["BATISTA RENZI", "ROBERTO BIANCHI", "LUIZ BIANCONI"],
          private: ["COLÉGIO SUZANO", "COLÉGIO EDUKI EDUCAÇÃO INFANTIL"],
          substitute: [
            "ZEIKICHI FUKUOKA",
            "ANTONIO GARCIA VEREADOR",
            "JARDIM SAO PAULO II",
          ],
        },
      },
      {
        name: "Patrícia Ferreira",
        role: "Supervisor",
        phone: "4746-6029",
        email: "patricia.ferreira04@educacao.sp.gov.br",
        shift: "4ª Feira das 15h as 17h",
        folders: [
          "PEI - ENSINO INTEGRAL",
          "TAREFAS",
          "SEINTEC",
          "AVALIAÇÃO DE DESEMPENHO",
          "ESTÁGIO PROBATÓRIO",
        ],
        schools: {
          public: [
            "ALFREDO ROBERTO",
            "JANDYRA COUTINHO PROFESSOR",
            "LUIZA HIDAKA PROFESSORA",
            "SEBASTIAO PEREIRA VIDAL",
          ],
          private: ["CETES -CENTRO EDUC. TECNICO SUZANENSE"],
          substitute: [
            "JOVIANO SATLER DE LIMA PROFESSOR",
            "MARIA ELISA DE AZEVEDO CINTRA PROFESSORA",
            "OSWALDO DE OLIVEIRA LIMA",
            "YOLANDA BASSI PROFESSORA",
          ],
        },
      },
      {
        name: "Raquel Tegedor Azevedo",
        role: "Supervisor",
        phone: "4746-6032",
        email: "raquel.azevedo@educacao.sp.gov.br",
        shift: "s/plantão",
        folders: ["EQUIVALENCIA DE ESTUDOS (SUBST)"],
        schools: {
          public: ["ZEIKICHI FUKUOKA"],
          private: [],
          substitute: [],
        },
        note: "AFASTADA - CONSELHO ESTADUAL DE EDUCAÇÃO",
      },
      {
        name: "Reni Gomes Pereira",
        role: "Supervisor",
        phone: "4746-6027",
        email: "reni.silva@educacao.sp.gov.br",
        shift: "3ª Feira das 10h as 12h",
        folders: [
          "PEI - ENSINO INTEGRAL",
          "SEGRE",
          "PROVA PAULISTA",
          "AVALIAÇÃO DE DESEMPENHO",
        ],
        schools: {
          public: [
            "DAVID JORGE CURI PROFESSOR",
            "LEDA FERNANDES LOPES PROFESSORA",
            "OSWALDO DE OLIVEIRA LIMA",
          ],
          private: ["COLÉGIO CRISTÃO KAIROS", "COLÉGIO CARVALHO"],
          substitute: [
            "ALFREDO ROBERTO",
            "CARLOS MOLTENI PROFESSOR",
            "GILBERTO DE CARVALHO PROFESSOR",
          ],
        },
      },
      {
        name: "Rosângela Simões dos Santos",
        role: "Supervisor",
        phone: "4746-7223",
        email: "rosangela.santos11@educacao.sp.gov.br",
        shift: "5ª Feira das 13h as 15h",
        folders: [
          "ESTAGIO PROBATÓRIO",
          "AULAS OLIMPICAS",
          "CONSELHO E APM (COLEGIADOS)",
          "APOIO PRESENCIAL",
          "CIPA",
        ],
        schools: {
          public: [
            "ANTONIO JOSE CAMPOS DE MENEZES PROFESSOR",
            "BENEDITA DE CAMPOS MARCOLONGO PROFES",
            "JOSE CAMILO DE ANDRADE",
            "TOCHICHICO YOCHICAVA PROFESSOR",
          ],
          private: [
            "PEQUENO PRINCIPE E PEQUENA PRINCESA EEI",
            "COLÉGIO AQUARELA",
          ],
          substitute: [
            "DAVID JORGE CURI PROFESSOR",
            "ELIANE AP. DANTAS DA SILVA PROFESSORA",
            "IIJIMA",
          ],
        },
      },
      {
        name: "Shirlene Geordania Pagliai",
        role: "Supervisor",
        phone: "4746-6030",
        email: "shirlenegeordania@educacao.sp.gov.br",
        shift: "5ª Feira das 15h as 17h",
        folders: [
          "CONSELHO MUNICIPAL SUZANO",
          "ENSINO TÉCNICO",
          "BEEM - BOLSA ESTÁGIO",
          "AULAS OLIMPICAS",
        ],
        schools: {
          public: [
            "JOSE PAPAIZ PROFESSOR",
            "CARLOS MOLTENI PROFESSOR",
            "IGNES CORREA ALLEN PROFESSORA",
            "OLZANETTI GOMES PROFESSOR",
          ],
          private: [
            "CENTRO EDUC. NIPO BRASILEIRA DE SUZANO",
            "COLÉGIO COLISEU",
          ],
          substitute: [
            "ANDERSON DA SILVA SOARES",
            "CARLINDO REIS",
            "LUIZ BIANCONI",
            "ROBERTO BIANCHI",
          ],
        },
      },
      {
        name: "Vanderlei Galindo",
        role: "Supervisor",
        phone: "4746-6031",
        email: "vanderlei.galindo@educacao.sp.gov.br",
        shift: "4ª Feira das 13h as 15h",
        schools: {
          public: [
            "ANTONIO VALDEMAR GALO VEREADOR",
            "OLAVO LEONEL FERREIRA PROFESSOR",
            "PAULO KOBAYASHI PROFESSOR",
          ],
          private: ["COLÉGIO DOM BOSCO", "COLÉGIO BETA"],
          substitute: [],
        },
      },
    ],
  },
  {
    sector: "EEC - Especialistas em Currículo",
    icon: "fa-book",
    color: "blue",
    members: [
      {
        name: "Daniella Lusni de Souza",
        role: "CEC",
        phone: "4746-7232",
        email: "daniella.souza@professor.educacao.sp.gov.br",
      },
      {
        name: "Alessandra Wink",
        role: "PEC",
        group: "Conviva",
        phone: "4746-5041 / 6041",
        email: "wink@professor.educacao.sp.gov.br",
      },
      {
        name: "Ari Oliveira Carvalho Junior",
        role: "PEC",
        group: "Desenvolvimento Curricular",
        phone: "4746-5036 / 6036",
        email: "aricarvalho@professor.educacao.sp.gov.br",
      },
      {
        name: "Fabiana Gomes Ramos da Silva",
        role: "PEC",
        group: "Desenvolvimento Curricular",
        phone: "***",
        email: "gomesramos@professor.educacao.sp.gov.br",
      },
      {
        name: "Jéssica Souza Kumagai",
        role: "PEC",
        group: "Desenvolvimento Curricular",
        phone: "4746-5042 / 6042",
        email: "jessicakumagai@professor.educacao.sp.gov.br",
      },
      {
        name: "José Vandei Silva de Oliveira",
        role: "PEC",
        group: "Desenvolvimento Curricular",
        phone: "4746-5037 / 6037",
        email: "josevandei@professor.educacao.sp.gov.br",
      },
      {
        name: "Mariana Pereira Santana Santos",
        role: "PEC",
        group: "Desenvolvimento Curricular",
        phone: "",
        email: "marianapsantana@professor.educacao.sp.gov.br",
      },
      {
        name: "Priscila Ribeiro da Silva",
        role: "PEC",
        group: "Desenvolvimento Curricular",
        phone: "***",
        email: "priscilars@professor.educacao.sp.gov.br",
      },
      {
        name: "Sandra Regina Soares Clemente",
        role: "PEC",
        group: "Desenvolvimento Curricular",
        phone: "4746-5038",
        email: "sandraclemente@professor.educacao.sp.gov.br",
      },
      {
        name: "Juliana Francisco de Oliveira Jaques",
        role: "PEC",
        group: "Educação Especial",
        phone: "",
        email: "jaques@professor.educacao.sp.gov.br",
      },
      {
        name: "Paula Margarete Alves",
        role: "PEC",
        group: "Educação Especial",
        phone: "4746-7216",
        email: "paulamargarete@professor.educacao.sp.gov.br",
      },
      {
        name: "Carla de Almeida Leite",
        role: "PEC",
        group: "Multiplica",
        phone: "",
        email: "carla.leite@educacao.sp.gov.br",
      },
      {
        name: "Marinete Pereira de Souza Oliveira",
        role: "PEC",
        group: "Multiplica",
        phone: "4746-5048 / 6048",
        email: "marineteoliveira@professor.educacao.sp.gov.br",
      },
      {
        name: "Midian de Almeida Pereira",
        role: "PEC",
        group: "Multiplica",
        phone: "***",
        email: "midianalmeida@professor.educacao.sp.gov.br",
      },
      {
        name: "Amanda Paula Rodrigues Teixeira",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "***",
        email: "amandaprodrigues@professor.educacao.sp.gov.br",
      },
      {
        name: "Ana Deise Lavor Firmino",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "4746-5050 / 6050",
        email: "analavor@professor.educacao.sp.gov.br",
      },
      {
        name: "Camila Santos Rocha",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "4746-7217",
        email: "camilasantosrocha@professor.educacao.sp.gov.br",
      },
      {
        name: "Claudia B.S. Mirandola",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "4746-5040 / 6040",
        email: "claudiamirandola@professor.educacao.sp.gov.br",
      },
      {
        name: "Fábio de Paula Ferraz",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "4746-7222",
        email: "fabioferraz@professor.educacao.sp.gov.br",
      },
      {
        name: "Lucas da Costa Henrique",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "",
        email: "lucasc@professor.educacao.sp.gov.br",
      },
      {
        name: "Marcelo Vicente Cavalcante da Silva",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "***",
        email: "marcelocavalcante@professor.educacao.sp.gov.br",
      },
      {
        name: "Núbia Miranda da Silva",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "***",
        email: "nubiamiranda@professor.educacao.sp.gov.br",
      },
      {
        name: "Simone Barone Yoshioka Salermo",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "",
        email: "sbaroni@professor.educacao.sp.gov.br",
      },
      {
        name: "Thais Aleksejuk Bernardes",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "4746-5043 / 6043",
        email: "aleksejuk@professor.educacao.sp.gov.br",
      },
      {
        name: "Valéria Santos França",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "4746-5039 / 6039",
        email: "valeriafranca@professor.educacao.sp.gov.br",
      },
      {
        name: "Verônica de Freitas Fiori",
        role: "PEC",
        group: "Qualidade da Aula",
        phone: "",
        email: "veronicafiori@professor.educacao.sp.gov.br",
      },
      {
        name: "Lais Guimarães Furst",
        role: "PEC",
        group: "Recomposição",
        phone: "4746-7251",
        email: "furst@professor.educacao.sp.gov.br",
      },
      {
        name: "Carlos Magno Precechan",
        role: "PEC",
        group: "Tecnologia",
        phone: "4746-5044 / 6044",
        email: "precechan@professor.educacao.sp.gov.br",
      },
    ],
    info: "E-mail do setor: suz.eec@educacao.sp.gov.br",
    link: "https://samucacs.github.io/fluxograma-ure/eec.html",
    linkLabel: "Conheça a EEC",
  },
  {
    sector: "SEGRE - Gestão da Rede Escolar",
    icon: "fa-school",
    color: "orange",
    members: [
      {
        name: "Maria Leonor Prado Callil",
        role: "Chefe de Serviço",
        phone: "4746-7237",
        email: "suz.segre@educacao.sp.gov.br",
      },
      {
        name: "Rodrigo Henrique M da Silva",
        role: "Chefe de Seção / SEVESC",
        phone: "4746-7239",
        email: "suz.sevesc@educacao.sp.gov.br",
      },
      {
        name: "Angela Oliveira",
        role: "SEVESC",
        phone: "4746-7260",
        email: "angela.oliveira@educacao.sp.gov.br",
      },
      {
        name: "Leonor Akiko Kamimura Uono",
        role: "SEVESC",
        phone: "4746-6019",
        email: "Leonor.uono@educacao.sp.gov.br",
      },
      {
        name: "Vanessa Pereira A. Gil",
        role: "Chefe de Seção / SEMAT",
        phone: "4746-7242",
        email: "suz.semat@educacao.sp.gov.br",
      },
      {
        name: "Henriqueta Rafaela S. Candido",
        role: "SEMAT",
        phone: "4746-7241",
        email: "suz.semat@educacao.sp.gov.br",
      },
      {
        name: "Joana Marrão",
        role: "SEMAT",
        phone: "4746-5056",
        email: "joana.marrao@educacao.sp.gov.br",
      },
      {
        name: "Ronaldo Spinola Nunes",
        role: "SEMAT / Assistente",
        phone: "4746-6016",
        email: "ronaldo.nunes@educacao.sp.gov.br",
      },
      {
        name: "Geovanna D'arc da Silva",
        role: "SEMAT / Estagiário",
        phone: "*",
        email: "es.geovanna@educacao.sp.gov.br",
      },
    ],
  },
  {
    sector: "SEINTEC - Tecnologia e Info",
    icon: "fa-laptop",
    color: "indigo",
    members: [
      {
        name: "Carlos Alexandre da Silva Camillo",
        role: "Chefe de Serviço / SEINTEC",
        phone: "4746-5021",
        email: "suz.seintec@educacao.sp.gov.br",
      },
      {
        name: "Samuel Carvalho da Silva",
        role: " Chefe de Seção / SETEC",
        phone: "4746-7258",
        email: "suz.setec@educacao.sp.gov.br",
      },
      {
        name: "Luiz Fabiano Camillo ",
        role: "Anlista de suporte Pleno",
        phone: "4746-7240",
        email: "suz.setec@educacao.sp.gov.br",
      },
      {
        name: "Bryan dos Santos Nascimento",
        role: "SEINTEC / Estagiário",
        phone: "",
        email: "suz.seintec@educacao.sp.gov.br",
      },
    ],
  },
  {
    sector: "SEAFIN - Admin e Finanças",
    icon: "fa-calculator",
    color: "teal",
    info: "Protocolo: 4746-7210",
    members: [
      {
        name: "Elaine Cristina Lopes",
        role: "Chefe de Serviço",
        phone: "4746-7231",
        email: "suz.seafin@educacao.sp.gov.br",
      },
      {
        name: "Ana Vitorina Dias",
        role: "Chefe de Seção / SEFIN",
        phone: "4746-7259",
        email: "suz.sefin@educacao.sp.gov.br",
      },
      {
        name: "Renato Alexandre Fumes",
        role: "SEFIN",
        phone: "4746-5052",
        email: "suz.sefin@educacao.sp.gov.br",
      },
      {
        name: "Joana D'Arc Custódia ",
        role: "SEFIN",
        phone: "4746-7252",
        email: "suz.sefin@educacao.sp.gov.br",
      },
      {
        name: "Jessica Muniz D. Ferreira",
        role: "Chefe de Seção / SECOMSE",
        phone: "4746-5057",
        email: "suz.secomse@educacao.sp.gov.br",
      },
      {
        name: "Veridiana dos Santos Vigantzky",
        role: "SECOMSE",
        phone: "4746-5011",
        email: "suz.secomse@educacao.sp.gov.br",
      },
      {
        name: "Zenailde",
        role: "SECOMSE",
        phone: "4746-5002",
        email: "suz.secomse@educacao.sp.gov.br",
      },
      {
        name: "Daniela",
        role: "SECOMSE",
        phone: "4746-6005",
        email: "suz.secomse@educacao.sp.gov.br",
      },
      {
        name: "Fábio Castro",
        role: "SECOMSE",
        phone: "4746-7247",
        email: "suz.secomse@educacao.sp.gov.br",
      },
      {
        name: "Wlanyse Pantoja Beckman",
        role: "SEFREP",
        phone: "4746-5001",
        email: "wlanyse.beckman01@educacao.sp.gov.br",
      },
      {
        name: "Joana D'arc Custódio",
        role: "SEFREP",
        phone: "4746-7252",
        email: "Joana.custodio@educacao.sp.gov.br",
      },
      {
        name: "Andréia Lopes dos Santos",
        role: "SEFREP",
        phone: "4746-5004",
        email: "andreia.santos02@educacao.sp.gov.br",
      },
      {
        name: "Dulceleia Archanjo Alves",
        role: "SEAFIN",
        phone: "4746-7248",
        email: "dulcileia.oliveira@educacao.sp.gov.br",
      },
    ],
  },
  {
    sector: "SEOM - Obras e Manutenção",
    icon: "fa-wrench",
    color: "red",
    members: [
      {
        name: "Lilian Barros Ramos de Oliveira",
        role: "Chefe de Serviço / SEOM",
        phone: "4746-7238",
        email: "suz.seom@educacao.sp.gov.br",
      },
      {
        name: "Dirnê de Sá Moraes Silva",
        role: "Chefe de Seção / SEFISC",
        phone: "4746-5003",
        email: "suz.sefisc@educacao.sp.gov.br",
      },
      {
        name: "Jefferson Paulino",
        role: "SEFISC",
        phone: "4746-6047",
        email: "suz.seom@educacao.sp.gov.br",
      },
      {
        name: "Elias Correia Francisco",
        role: "SEOM / Assistente",
        phone: "Sem ramal",
        email: "elias.francisco@educacao.sp.gov.br",
      },
      {
        name: "Amilton Chagas da Silva Vitor",
        role: "SEOM / Assistente",
        phone: "4746-6047",
        email: "suz.seom@educacao.sp.gov.br",
      },
    ],
  },
  {
    sector: "SEPES - Serviço de Pessoas",
    icon: "fa-users",
    color: "pink",
    members: [
      {
        name: "Taynã Iara da Silva Pinto Moura",
        role: "Chefe de Serviço / Sepes",
        phone: "4746-5006",
        email: "suz.sepes@educacao.sp.gov.br",
      },
      {
        name: "Laiene Cavalcante do Pradoo",
        role: "Chefe de Seção / SEAPE",
        phone: "4746-7249",
        email: "suz.seape@educacao.sp.gov.br",
      },
      {
        name: "Cristina do Vale",
        role: "Chefe de Seção / SEFREP",
        phone: "4746-7245",
        email: "suz.sefrep@educacao.sp.gov.br",
      },
      {
        name: "Gutemberg Melo",
        role: "SEPES",
        phone: "Sem ramal",
        email: "gutemberg.melo@educacao.sp.gov.br",
      },
      {
        name: "Aline Cardoso de Sá",
        role: "SEAPE",
        phone: "4746-7250",
        email: "aline.sa02@educacao.sp.gov.br",
      },
      {
        name: "Fran Galvão",
        role: "SEAPE",
        phone: "4746-5009",
        email: "francinalva.galvao@educacao.sp.gov.br",
      },
      {
        name: "Luiz Barros Orfão",
        role: "SEAPE",
        phone: "4746-5010",
        email: "luiz.orfao@educacao.sp.gov.br",
      },
      {
        name: "Mario Mendes Leal Filho",
        role: "SEAPE",
        phone: "4746-7255",
        email: "mario.mendes03@educacao.sp.gov.br",
      },
      {
        name: "Regina Ramos de Lima Vieira",
        role: "SEAPE",
        phone: "4746-5012",
        email: "regina.vieira04@educacao.sp.gov.br",
      },
      {
        name: "Rita de Cássia Castro Souza",
        role: "SEAPE",
        phone: "4746-7230",
        email: "rita.souza05@educacao.sp.gov.br",
      },
      {
        name: "Maria Inaídes Pereira Góes",
        role: "SEAPE",
        phone: "4746-7254",
        email: "maria.goes08@educacao.sp.gov.br",
      },
      {
        name: "Angelica Rodrigues Sousa de Oliveira",
        role: "SEFREP",
        phone: "4746-5015",
        email: "angelica.oliveira04@educacao.sp.gov.br",
      },
      {
        name: "Eliane Durval da Silva",
        role: "SEFREP",
        phone: "4746-7234",
        email: "eliane.silva01@educacao.sp.gov.br",
      },
      {
        name: "Clayton Souza Barriento",
        role: "SEFREP",
        phone: "4746-5018",
        email: "clayton.barriento@educacao.sp.gov.br",
      },
      {
        name: "Wilma Aparecida de Rezende",
        role: "SEFREP",
        phone: "4746-7229",
        email: "wilma.rezende@educacao.sp.gov.br",
      },
      {
        name: "Iva Rosa Santos de Oliveira",
        role: "SEFREP",
        phone: "4746-5013",
        email: "iva.santos01@educacao.sp.gov.br",
      },
      {
        name: "Erika Karen Vitor F. da Silva",
        role: "SEFREP",
        phone: "4746-7215",
        email: "erika.barbosa@educacao.sp.gov.br",
      },
      {
        name: "Daniela Soares Silva Resende",
        role: "SEFREP",
        phone: "4746-5017",
        email: "daniela.resende@educacao.sp.gov.br",
      },
    ],
  },
];

// Atalhos exibidos na coluna lateral.
const quickLinks = [
  {
    label: "Fluxograma da URE",
    description: "Organograma e atribuições dos setores",
    href: "https://samucacs.github.io/fluxograma-ure/",
    icon: "fa-diagram-project",
    color: "green",
  },
  {
    label: "Supervisão de Ensino",
    description: "Plantões, escolas e pastas",
    href: "https://pagina-supervisao-ese.vercel.app/",
    icon: "fa-eye",
    color: "purple",
  },
  {
    label: "Especialistas em Currículo",
    description: "Equipe e atribuições da EEC",
    href: "https://samucacs.github.io/fluxograma-ure/eec.html",
    icon: "fa-book",
    color: "blue",
  },
];

// Números e e-mails mais procurados, exibidos na coluna lateral.
const usefulNumbers = [
  {
    label: "Recepção do Gabinete",
    value: "4746-7214 | 4746-7220",
    type: "phone",
  },
  {
    label: "Plantão da Supervisão",
    value: "4746-7227 / 4746-7228",
    type: "phone",
  },
  {
    label: "Protocolo (SEAFIN)",
    value: "4746-7210",
    type: "phone",
  },
  {
    label: "E-mail do Gabinete",
    value: "suz@educacao.sp.gov.br",
    type: "email",
  },
  {
    label: "E-mail da EEC",
    value: "suz.eec@educacao.sp.gov.br",
    type: "email",
  },
];
